version: "3"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maven_container1
    image: builder:latest
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dd
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  tomcat:
    build:
      context: .
      dockerfile: T.Dockerfile
    image: tomcat:latest
    ports:
      - 8080:8080
    depends_on:
      - builder
      - db
    volumes:
      - ./WebContent:/usr/local/tomcat/ROOT/
    container_name: tomcat-container2
    restart: unless-stopped

