version: "3"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maven_container1
    image: builder:latest
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DATABASE: dd
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "8514:8514"

  tomcat:
    build:
      context: .
      dockerfile: T.Dockerfile
    image: tomcat:latest
    ports:
      - 8080:8080
    depends_on:
      - builder
      - db
    volumes:
      - ./WebContent:/usr/local/tomcat/ROOT/
    container_name: tomcat-container2
    restart: unless-stopped

